version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  calendar-assistant-1:
    build: .
    ports:
      - "8001:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - SUPERVISOR_ID=supervisor-1
      - LOG_LEVEL=INFO
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./google_credentials:/app/google_credentials:ro
    restart: unless-stopped

  calendar-assistant-2:
    build: .
    ports:
      - "8002:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - SUPERVISOR_ID=supervisor-2
      - LOG_LEVEL=INFO
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./google_credentials:/app/google_credentials:ro
    restart: unless-stopped

  calendar-assistant-3:
    build: .
    ports:
      - "8003:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - SUPERVISOR_ID=supervisor-3
      - LOG_LEVEL=INFO
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./google_credentials:/app/google_credentials:ro
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - calendar-assistant-1
      - calendar-assistant-2
      - calendar-assistant-3
    restart: unless-stopped

volumes:
  redis_data: 